name: Build & Release

on:
  push:
    tags: ['v*']

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - name: Build on Ubuntu
        run: cargo build --release
      - name: Upload Artifacts from Ubuntu
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu
          path: target/release/a-shell

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - name: Build on macOS
        run: cargo build --release
      - name: Upload Artifacts from macOS
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: target/release/a-shell

  release:
    needs: [build-ubuntu, build-macos]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Ubuntu Artifacts
        uses: actions/download-artifact@v3
      - name: Download macOS Artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: ''
          prerelease: false
          files: |
            ubuntu
            macos
